# =============================================================================
# Homepage Ingress (Protected by OAuth2 Proxy)
# =============================================================================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: utilities
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nerine.dev`)
      kind: Rule
      services:
        - name: homepage
          port: 80
      middlewares:
        - name: public-chain
          namespace: traefik
        - name: oauth2-proxy
          namespace: traefik
  tls:
    certResolver: letsencrypt
    domains:
      - main: nerine.dev
        sans:
          - "*.nerine.dev"
