apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
  namespace: media
spec:
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: prowlarr
    spec:
      initContainers:
        - name: config-initializer
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            [
              " if [ ! -f /config/config.xml ]; then cp /config-template/config.xml /config/; fi ",
            ]
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
            - name: arr-config
              mountPath: /config-template
              readOnly: true
      containers:
        - env:
            - name: TZ
              value: Europe/Warsaw
          image: linuxserver/prowlarr:2.3.0
          name: prowlarr
          ports:
            - containerPort: 9696
          volumeMounts:
            - mountPath: /config
              name: prowlarr-data
      restartPolicy: Always
      volumes:
        - name: arr-config
          configMap:
            name: arr-config
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data
