# =============================================================================
# Immich Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - ml-deployment.yaml

commonLabels:
  app.kubernetes.io/name: immich
