apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qbittorrent
  name: qbittorrent
  namespace: media
spec:
  selector:
    matchLabels:
      io.kompose.service: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: qbittorrent
    spec:
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args: ["cp /defaults/config.conf /config/qBittorrent.conf"]
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-data
            - mountPath: /defaults
              name: qbittorrent-config
      containers:
        - env:
            - name: DOCKER_MODS
              value: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
            - name: TZ
              value: Europe/Warsaw
            - name: UMASK
              value: "002"
          image: linuxserver/qbittorrent:20.04.1
          name: qbittorrent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config/qBittorrent
              name: qbittorrent-data
            - mountPath: /data
              name: qbittorrent-storage
      restartPolicy: Always
      volumes:
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: qbittorrent-data
        - name: qbittorrent-config
          configMap:
            name: qbittorrent-config
        - name: qbittorrent-storage
          hostPath:
            path: /Storage
