# =============================================================================
# AdGuard Home Ingress (Protected by OAuth2 Proxy - Web UI)
# =============================================================================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.nerine.dev`)
      kind: Rule
      services:
        - name: adguard
          port: 3000
      middlewares:
        - name: public-chain
          namespace: traefik
        - name: oauth2-proxy
          namespace: traefik
  tls: {}
