# =============================================================================
# AdGuard Home Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

configMapGenerator:
  - name: adguard-config
    namespace: home
    files:
      - AdGuardHome.yaml

commonLabels:
  app: adguard
