# =============================================================================
# AdGuard Home Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home

resources:
  - deployment.yaml
  - service.yaml
  - service-tailscale.yaml
  - ingress.yaml
  - pvc.yaml
  - middleware.yaml

configMapGenerator:
  - name: adguard-config
    namespace: home
    files:
      - AdGuardHome.yaml

labels:
  - pairs:
      app: adguard
    includeSelectors: true
