# =============================================================================
# Proxmox Host Configuration Variables
# =============================================================================

# ZFS Storage Configuration
zfs_pool_name: Storage
zfs_storage_size: 8T

# iSCSI Configuration
iscsi_target_iqn: iqn.2026-01.dev.nerine:k8s
