apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: homepage
  name: homepage
  namespace: utilities
spec:
  selector:
    matchLabels:
      io.kompose.service: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: homepage
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Warsaw
          image: ghcr.io/gethomepage/homepage:v1.10.1
          name: homepage
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/config
              name: homepage-data
      restartPolicy: Always
      volumes:
        - name: homepage-data
          persistentVolumeClaim:
            claimName: homepage-data
