# TalosOS Cluster Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfs-storage-config.yaml
  - bootstrap/
  - apps/

replacements:
  - source:
      kind: ConfigMap
      name: nfs-storage-config
      fieldPath: data.server
    targets:
      - select:
          kind: PersistentVolume
          name: media-nfs-pv
        fieldPaths:
          - spec.nfs.server
      - select:
          kind: PersistentVolume
          name: media-nfs-pv-utilities
        fieldPaths:
          - spec.nfs.server
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - parameters.server
  - source:
      kind: ConfigMap
      name: nfs-storage-config
      fieldPath: data.path
    targets:
      - select:
          kind: PersistentVolume
          name: media-nfs-pv
        fieldPaths:
          - spec.nfs.path
      - select:
          kind: PersistentVolume
          name: media-nfs-pv-utilities
        fieldPaths:
          - spec.nfs.path
      - select:
          kind: StorageClass
          name: nfs-csi
        fieldPaths:
          - parameters.share

labels:
  - includeSelectors: false
    pairs:
      cluster: talos
      managed-by: argocd
