# =============================================================================
# Decluttarr Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - deployment.yaml

configMapGenerator:
  - name: decluttarr-config
    namespace: media
    files:
      - config.yaml

labels:
  - pairs:
      app: decluttarr
    includeSelectors: true
