# =============================================================================
# qBittorrent External Secrets
# =============================================================================
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-webui
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store
    kind: ClusterSecretStore
  target:
    name: qbittorrent-webui
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: qbittorrent-username
    - secretKey: password
      remoteRef:
        key: qbittorrent-password
