# =============================================================================
# qBittorrent Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - deployment.yaml
  - externalsecret.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

labels:
  - pairs:
      app: qbittorrent
    includeSelectors: true
