# =============================================================================
# Sonarr Kustomization
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - deployment.yaml
  - service-tailscale.yaml

labels:
  - pairs:
      app: sonarr
    includeSelectors: true
