name: Kubernetes Apply

on:
  workflow_dispatch:

concurrency:
  group: concurrency-lock
jobs:
  kubectl-apply:
    runs-on: ubuntu-latest
    environment: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: "true"
          version: latest

      - name: Get kubeconfig
        run: |
          mkdir -p $HOME/.kube
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@nickel:/etc/rancher/k3s/k3s.yaml $HOME/.kube/config
          sed -i 's/127.0.0.1/nickel/' $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl kustomize Kubernetes/ --enable-helm | kubectl apply -f -

      - name: Remove kubeconfig
        run: rm -rf $HOME/.kube
